services:
    phone_backend:
      container_name: phone_ms
      build: .
      volumes:
        - .:/app
      expose:
        - 9000
      networks:
        - phone

    nginx:
      image: nginx:stable-alpine
      container_name: phone_ms_nginx
      ports:
        - "8077:80"
      volumes:
        - .:/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - phone_backend
      networks:
        - phone

#    phone_db:
#      container_name: phone_ms_db
#      image: mysql:8
#      restart: always
#      environment:
#        MYSQL_DATABASE: check
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_PASSWORD: root
#      ports:
#        - 33066:3306
#      networks:
#        - phone

networks:
  phone:
    name: phone
